/* Generated By:JavaCC: Do not edit this line. GrammarConstants.java */
package parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface GrammarConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NOT = 6;
  /** RegularExpression Id. */
  int SEMICOLON = 7;
  /** RegularExpression Id. */
  int COMMA = 8;
  /** RegularExpression Id. */
  int EQUALS = 9;
  /** RegularExpression Id. */
  int LOWER_WORD = 10;
  /** RegularExpression Id. */
  int UPPER_WORD = 11;
  /** RegularExpression Id. */
  int LOWER_ALFA = 12;
  /** RegularExpression Id. */
  int UPPER_ALFA = 13;
  /** RegularExpression Id. */
  int NUMERIC = 14;
  /** RegularExpression Id. */
  int ZERO_NUMERIC = 15;
  /** RegularExpression Id. */
  int NON_ZERO_NUMERIC = 16;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "\"!\"",
    "\";\"",
    "\",\"",
    "\"=\"",
    "<LOWER_WORD>",
    "<UPPER_WORD>",
    "<LOWER_ALFA>",
    "<UPPER_ALFA>",
    "<NUMERIC>",
    "<ZERO_NUMERIC>",
    "<NON_ZERO_NUMERIC>",
    "\"(\"",
    "\")\"",
  };

}
